### ISSUE TITLE
In order to have a nicer location marker on the location screen, as a user I want the current menu icon changed

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#101]
It can be a drop down arrow next to the location name or at the menu icon location or also location icon (pin) there instead of the current icon.

**Comment by wilfredstegeman** [comment]
I suggest to use a drop down arrow (open or closed) next to the location. This is also used by Meetup and Eventbrite, feels very natural. In contrast to for instance 'All events in city' where they've disconnected the two with a location picked icon in the right top corner. 


		


_____________________________

**Comment by lemonboston** [comment]
Started working on adding the drop-down arrow next to the title.

Work items checklist (updated continuously):

- [x] Check what are the options for implementation -> 1. Adding unicode character 2. Using ImageSpan and icon 3. Maybe some special fonttype/typeface

- [x] Try unicode character -> none of them looked good exactly and they might change if device use different font, also it strangely took 1-2 sec to load the screen after this change (maybe Android initializes a bigger character set?) -> solution dropped

- [x] Try with ImageSpan -> works

- [x] Create proper class to handle text and icon -> TextWithIcon created (custom spannable string design may be improved later if needed)

- [x] Remove location icon from menu

- [x] Bug noticed: slight vertical misalignment of the title -> cause: the icon is a bit bigger than the text -> options to fix: 1. fix alignment to center (-> didn't work) 2. resize the icon asset 3. resize the image in code 4. try to use vector asset instead of the png -> vector asset worked

- [x] Refine drop-down vector icon geometry

- [x] Change Toolbar to not fire onClick for the whole length, only for the title -> need to add a TextView inside the Toolbar, can't change this on Toolbar itself

- [x] Update left margin/padding adjustment logic for the case when there is no UP arrow, for the new TextView title -> after a first hack, found contentInset property of Toolbar which is exactly for this

- [x] Handle long titles (single line with dots) -> used android:ellipsize="middle", because "end" causes drop down to not shown fully, also it might make sense to use middle, we don't know which part of a long venue name is important, start or end

- [x] Double-check on earlier Android versions
