### ISSUE TITLE
Day headers on Android 4.1 show "in 0 days" and "tomorrow"

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#105]
.. instead of "Today" and "Tomorrow"

Android Emulator, Nexus 5, API 16 (=Android 4.1):

![device-2017-01-30-153329](https://cloud.githubusercontent.com/assets/1077972/22426999/bb5100e0-e701-11e6-9655-65c15c55d1a1.png)

**Comment by dmfs** [comment]
That's probably a live bug. Isn't it?

**Comment by lemonboston** [comment]
Yes, probably.

**Comment by lemonboston** [comment]
Work items (updated continuously):

- [X] Research what can cause this different behaviour of DateUtils in earlier Android versions -> found nothing

- [X] Check if bug happens on real device as well -> eventually was able to test on a cloud service backed by real devices, on an Android 4.1 phone -> yes, the bug is there

- [X] Update code to use 'hardcoded' localized strings "Today", "Tomorrow" for the affected Android versions, otherwise use DateUtils

- [x] Check with all available Android emulators shipped with Android SDK which versions are affected

- [x] Turns out DateHeaderFormatAndroid behaves differently with different Android versions, update it accordingly -> got very complicated, left a TODO in code
