### ISSUE TITLE
Enable hardware acceleration by default.

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#112]
In order to get a smooth experience, as a user I want the SDK to use hardware acceleration whenever possible.

Some partner apps might have disabled HW acceleration by default. We'll enable it explicitly for our activities in the AndroidManifest.

**Comment by lemonboston** [comment]
Duplicate of https://github.com/schedjoules/android-event-discovery-sdk/issues/92, I suppose that one can be closed.

**Comment by dmfs** [comment]
Oh, yes of course. I'll close the other one.
