### ISSUE TITLE
Add map to details page

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#139]
In order to see the location of a venue, as a user I want a map on the details page.

**Comment by lemonboston** [comment]
@dmfs Could you please get an API key that's enabled for Google Maps API possibly with the GET KEY button here:
https://developers.google.com/maps/documentation/android-api/map-with-marker
I assume it can be enabled for the same project as where we have the API key for the Places API, not sure if it generates a modified key, or the existing one can be used.

**Comment by lemonboston** [comment]
Probably also worth looking at this about the production project and premium plans:
https://developers.google.com/maps/documentation/android-api/signup

**Comment by lemonboston** [comment]
@dmfs Should we be prepared that the partner's Google API key is only enabled for Places (autocomple suggestion queries) and not for the Maps?

The usage for both is the same, just a manifest entry:
```
<meta-data
                android:name="com.google.android.geo.API_KEY"
                android:value="${googlePlacesApiKey}"/>
```
So I suggest we change the name of the variable to let's say `googleApiKey`, and also I think it would be better to fail the build if the local property is not present. (CI would be secondary to this imo, I would rather do some workaround for that then to let SDK be used incorrectly.) Okay to make those changes?

Working solution is on branch `stories/139-add-map-to-event-details` already if you want to check it out. (Not really ready for review but feel free to comment of course.)
I would like to sort out the location requirements first ( https://github.com/schedjoules/event-discovery-backend/issues/37) before finalizing to avoid complicating with optional scenarios that don't exist.

**Comment by dmfs** [comment]
You're mixing something up here. That local property is only used in the demo app (so we don't have to publish our key with the SDK). Partners usually add their key directly to their Manifest. Also partners pull the SDK in as a Maven dependency, so none of our Gradle code is executed and we have no way to enforce at compile time that a key is present.

Also, if a build would fail if there is no local property, we couldn't distribute via Jitpack, because Jitpack wouldn't be able to build it.

Yes, we have to be prepared that no Google services are available or that we can't use them (because there is no key or it's not enabled for Maps). In short all Google Maps functionality needs to be optional.

**Comment by dmfs** [comment]
Can we have the map to be scrolled with two fingers instead of just one? Having scrollable content inside of a scrollable page can be frustrating when you hit the map by accident when you want to scroll. Especially in landscape mode it can be hard to scroll up again because the map covers almost the entire scrollable screen.
Google actually came up with a solution to that. When you embed a Map in a website (using the Javascript API), it requires two fingers to scroll by default. I've seen that in our event webview. If that's not possible on Android, try to disable scrolling altogether. Users should open Google Maps in that case.

**Comment by lemonboston** [comment]
Thanks, right, I did mixed that up, that property is only in the demo app. So I don't plan to change anything there then.

I am going to look into how can we check programatically if Maps is enabled to make that functionality optional.

I will also check the double finger scrolling.

**Comment by lemonboston** [comment]
Update on the how to check if Maps is available question:

I ran the app with an invalid API key, an empty map is still shown, there is only a logcat error. 
```
04-12 10:25:38.884 E/Google Maps Android API: Authorization failure.  Please see https://developers.google.com/maps/documentation/android-api/start for how to correctly set up the map.
04-12 10:25:38.886 E/Google Maps Android API: In the Google Developer Console (https://console.developers.google.com)
                                              Ensure that the "Google Maps Android API v2" is enabled.
                                              Ensure that the following Android Key exists:
                                              	API Key: sdfAIzaSyDqfO...MAJ1_0PxAA6d
                                              	Android Application (<cert_fingerprint>;<package_name>): C4:32:39...
```
So `onMapReady(GoogleMap googleMap)` callback is called with a `GoogleMap` object and no exceptitons.
https://developers.google.com/android/reference/com/google/android/gms/maps/MapsInitializer
this also returns success code.
An SO question: 
http://stackoverflow.com/questions/22608787/android-programmatically-validate-google-map-key-in-application
Maybe it would be also worth checking with an API key that is valid but not enabled for Maps.

What we could do is fire a manual request to the Maps API to check for error.

**Comment by dmfs** [comment]
Yes, I guess we have to check with an API request then. Please don't spend too much time on the two finger scroll. I wouldn't mind if a tap on the map just launches the Maps App instead. We can improve that later on.
