### ISSUE TITLE
Split address field into venue and address

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#141]
In order to see the important details of the event in the same area, as a user I want the venue to be a separate field right underneath the title area while the address stays close to the map on the bottom.
---
For now the "directions" action is attached to the address field, whereas the venue doesn't have an action. This will be part of a separate story, because it requires a few changes on the list view.

**Comment by lemonboston** [comment]
Implemented in #138, moving this to Review column as well.
