### ISSUE TITLE
Country Coverage Service call

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#143]
In order to determine whether to show the event discovery entry point, as a partner I want a convenient way to check the county coverage.
---

The challenge is that partners usually need to know the result before the user gets to see the entry point. I.e. The result must already be available when the user sees the button to open a menu that contains the entry point option.

That means partners need to start a service or something similar with the activity that contains the entry point.
The problem with a service is that it always requires an asynchronous operation (to bind it). It might be easier to use a `ContentProvider` instead which can be called synchronously if it returns fast enough.

The result must be cached for one week or until the user has moved significantly (e.g. one of the country codes is different)

**Comment by rutgerg** [comment]
I updated the order of checking to GPS > Operator > SIM > Region > GEO IP

**Comment by lemonboston** [comment]
Should there be a story to update the SDK Wiki about this topic and describe the usage?
