### ISSUE TITLE
Make sure items on recent locations are unique

### ISSUE THREAD

**Issue by rutgerg** [schedjoules/android-event-discovery-sdk#145]
![75c2aae6-89eb-429f-8020-16d35ceefae7](https://cloud.githubusercontent.com/assets/676860/23851671/a263c65e-07e4-11e7-9333-0cfa1165ed48.jpeg)

**Comment by dmfs** [comment]
That happens when you use "current location". Since your current location is unlikely to be the same for two different lookups, you'll see it as two entries (so in fact they bot refer to different geo locations)
I suggest to not add "current locations" to the recent locations at all.

**Comment by lemonboston** [comment]
This has been resolved in #142 by not saving current location selection to recent locations.
