### ISSUE TITLE
Change the name of the actual current location in 'Current location'

### ISSUE THREAD

**Issue by wilfredstegeman** [schedjoules/android-event-discovery-sdk#146]

**Comment by lemonboston** [comment]
@wilfredstegeman Could you please explain this a bit more, what would you like to change to what, maybe with an example? Thanks.

**Comment by wilfredstegeman** [comment]
Check the example from Eventbrite, which is how all 'Current location' options are set up. They have named their current location option actually 'Current location' and not eg 'Amsterdam', like in our setup. In the example of Eventbrite a user doesn't get confused between two versions of Amsterdam with different results. When you choose Amsterdam from 'Recent searches' a users expects events from Amsterdam and probably all. In the case of 'Current location' a users expects events around him, which could be set to eg 1 kilometer around him. Still in Amsterdam but on a different scale, as expected.

![image uploaded from ios 4](https://cloud.githubusercontent.com/assets/5968782/23862110/79d88364-080c-11e7-8430-03650b22dfd2.jpg)

**Comment by lemonboston** [comment]
I see, makes sense, thanks.

**Comment by lemonboston** [comment]
@wilfredstegeman @dmfs We could also do something like
"Current location (in Amsterdam)"
"Current location in Amsterdam"
"Current location (within Amsterdam)"
Not sure if that is better, but let me know if you happen to prefer anything like that over "Current location".

**Comment by dmfs** [comment]
I think the Text "Current Location" should be styled like a borderless button (similar to the Eventbrite example). In particular it should use CAPS and accent color (also see the retry button in #151) If the location has already been resolved we could add it as a second line underneath (just the locality name, i.e. the city)
