### ISSUE TITLE
Current location - retry

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#151]
In order to know exactly where to tap, as a user I want a button that says "retry" when my location can not be determined.
---

See:
![device-2017-03-16-102744](https://cloud.githubusercontent.com/assets/1614987/23991901/3e563620-0a3b-11e7-9986-898dfcce2c93.png)

The button should right (end) aligned and either vertically centered or bottom aligned (with the usual margin), whatever looks best. The error message might have to be two lined in some languages.

**Comment by lemonboston** [comment]
This is part of #147.

**Comment by dmfs** [comment]
This has been implemented already.
