### ISSUE TITLE
Create fix layout for details page elements instead of the dynamically populated actions

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#162]
## In order to use the app effectively, as a user I want all UI elements on the details page to have a fix place where I can expect them.

In order to switch to this approach, we need to have a fix layout where the items have a fix placeholder.

**Comment by lemonboston** [comment]
@rutgerg , @dmfs , @wilfredstegeman 
Just to be on the safe side, could someone please confirm that the API only sends 'add to calendar', 'share', 'directions' actions currently, so we don't already use any of the earlier defined actions?:

info, call, buy, remind, watch, invite

(They are supported now in the app, but if we switch to fix layout we need to define place for them, if they are used.)

**Comment by dmfs** [comment]
This is not about what the API sends, but what we're going to present to the user. For now that's "add to calendar", "share" and "directions".

**Comment by lemonboston** [comment]
I think this is not worth starting until #161 , #163 and #164 are reviewed and merged.

**Comment by lemonboston** [comment]
@dmfs , @wilfredstegeman Could you please provide translation for the new share button label?:
Tip a Friend
(It will be displayed in caps.)

**Comment by wilfredstegeman** [comment]
@lemonboston Keep 'Share' for now. Not sure about the Tip a friend at this moment. In Dutch that is 'Delen'.
