### ISSUE TITLE
action text capitals

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#168]
In order to identify clickable actions quickly, as user I want actions to be styled like buttons.
---
Actions should use a borderless button style and span the entire line (i.e. don't use a `wrap_content` width) The only concession we make to the design is that actions have black text (`#515457` to be more precise).

**Comment by lemonboston** [comment]
I suppose it's worth doing after #162 or as part of that.

**Comment by lemonboston** [comment]
Closing this, as this is addressed in #178 and #183 .
