### ISSUE TITLE
Fine tuning at the end of Update Design Phase 1

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#183]
We will collect here the small outstanding issues or discrepancies between the design and the look that were not worth addressing in the bigger stories.

This will also give us a chance to review the whole screen after all components are in place and compare to design again.

---

- [x] 1. Description text and icon alignments. Currently both have 16dp margin, but as the material icons have a standard 2dp padding, they are not aligned. Moreover some icons, like the _location pin_ one for the venue name is even slimmer, so has empty horizontal space beside the 2dp padding, so it's left edge won't align with the text, as it is done on the design.
Simply increasing description text margin to 18dp has the concern of leaving the 8dp grid.

- [x] 2. Directions address text size. It is 14sp size currently instead of 16sp as on the design, because it uses the same view as the other actions which have 14sp

- [x] 3. Action view text styles. The capital case is applied in code dynamically currently because the directions label have normal case. Directions could however get dedicated layout as well.
It was suggested to use style for capital case and maybe use BorderlessButton style. Get back to all this if needed. 

- [x] 4. Divider color. The 12% transparency one, which material specs say looked too light with the 1px height. Check again and decide.

- [x] 5. (Optional) Review colors, styles, dimens usage:
Review colors.xml, styles.xml, make any common sense changes, then look through the event details related layouts again to use those or new styles where it make sense. Maybe also create named dimens for text sizes. Maybe communicate color palette and usage to ui-ux channel.

- [x] 6. Check if it make sense to apply our primary and secondary text colors as theme properties. For example location picker item second line now use default theme color just as all TextViews where we may forget to specify, so I guess it would probably make sense to update the theme.
We may be able to use `tertiary` color as well, just found this:
```
        <!-- The most prominent text color.  -->
        <attr name="textColorPrimary" format="reference|color" />
        <!-- Secondary text color. -->
        <attr name="textColorSecondary" format="reference|color" />
        <!-- Tertiary text color. -->
        <attr name="textColorTertiary" format="reference|color" />
```
in `android-sdk/platforms/android-23/data/res/values/attrs.xml`. Although not sure what widgets use that and for what.

- [x] 7. Review distances between elements.
(One in particular: action icon and text distance is 18dp now, probably can be 24dp to fit the grid.)

- [x] 8. Event details loader screen doesn't look very nice (black title, loading message not in the middle) - see screenshot in commennts

**Comment by lemonboston** [comment]
- [ ] 1. Description text and icon alignments. Currently both have 16dp margin, but as the material icons have a standard 2dp padding, they are not aligned. Moreover some icons, like the _location pin_ one for the venue name is even slimmer, so has empty vertical space beside the 2dp padding, so it's left edge won't align with the text, as it is done on the design.
Simply increasing description text margin to 18dp has the concern of leaving the 8dp grid.

**Comment by lemonboston** [comment]
- [ ] 2. Directions address text size. It is 14sp size currently instead of 16sp as on the design, because it uses the same view as the other actions which have 14sp

- [ ] 3. Action view text styles. The capital case is applied in code dynamically currently because the directions label have normal case. Directions could however get dedicated layout as well.
It was suggested to use style for capital case and maybe use BorderlessButton style. Get back to all this if needed.

**Comment by lemonboston** [comment]
- [ ] 4. Divider color. The 12% transparency one, which material specs say looked too light with the 1px height. Check again and decide.

**Comment by lemonboston** [comment]
- [ ] 5. (Optional) Review colors, styles, dimens usage:
Review colors.xml, styles.xml, make any common sense changes, then look through the event details related layouts again to use those or new styles where it make sense. Maybe also create named dimens for text sizes. Check if it make sense to apply primary and secondary text color as theme properties. Maybe communicate color palette and usage to ui-ux channel.

**Comment by lemonboston** [comment]
- [ ] 6. Review distances between elements.
(One in particular: action icon and text distance is 18dp now, probably can be 24dp to fit the grid.)

**Comment by dmfs** [comment]
Please move add all the check marks to the description of the story and remove the individual comments. It's easier to follow that way.

**Comment by lemonboston** [comment]
Ok, done.

**Comment by lemonboston** [comment]
For item 8.:

![device-2017-04-12-101147](https://cloud.githubusercontent.com/assets/1077972/24947886/b981ec08-1f68-11e7-9797-5ef7d62fb090.png)

**Comment by dmfs** [comment]
4 has already been fixed. Dividers are 12% transparency but `1dp` instead of `1px` in width.

**Comment by dmfs** [comment]
Created #224 for checkbox no 3.

**Comment by dmfs** [comment]
1 and 7 are covered by #225

**Comment by dmfs** [comment]
5 is halfway done. Dimensions will be part of the tablet layout overhaul

**Comment by dmfs** [comment]
2 is covered by #226

**Comment by dmfs** [comment]
@wilfredstegeman regarding the loader screen above, that's what a user would see when he opens the event directly (like with a deep link or directly from the event view of the partner app). In that case the event needs to be loaded first, so nothing about the event is known at that time, hence the blank loader screen.
What can we do to improve this view (aside from moving the message to the center of the screen)?
Also created schedjoules/backlog#184 to improve the loader animation

**Comment by wilfredstegeman** [comment]
An option could be to show a content placeholder like Facebook. 

![content-placeholder](https://cloud.githubusercontent.com/assets/5968782/25428378/f6345a10-2a75-11e7-968b-823c1a753df7.jpg)]

This could look something like this:

![content-placeholder-schedjoules](https://cloud.githubusercontent.com/assets/5968782/25428690/d9d8b7f2-2a76-11e7-82dc-0776ae45d868.jpg)

Or only show a SchedJoules activity loader:

![content-placeholder-schedjoules-exclusive](https://cloud.githubusercontent.com/assets/5968782/25429238/9fa599fe-2a78-11e7-8f8d-640605497f86.jpg)

**Comment by dmfs** [comment]
I like the placeholder, maybe combined with some sort of progress indicator (so the user knows it's working in the background).

**Comment by lemonboston** [comment]
I like those placeholders, too. That could be a bigger task, I suppose we could create a story for that and prioritize later.

And in the meantime, could we apply a quicker fix for that load screen? Changing "Loading event.." text color to white, the background to something bit darker (maybe faded accent color), and just removing "This might take a moment" message.

Let me know whether this sounds good so I can create the story and the bug.

**Comment by wilfredstegeman** [comment]
Can't we just show an activity loader on an entire white screen to start with? For instance the Schedjoules one that we already have, three dots of Airbnb, or one of the dotted ones from the example from @dmfs.

**Comment by dmfs** [comment]
Created story #269 to cover point 8. This story is obsolete now.
