### ISSUE TITLE
Rename event details loader layouts

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#190]
See https://github.com/schedjoules/android-event-discovery-sdk/pull/178#pullrequestreview-31585294.

My intention with renaming the 4 event details screen related fragment layouts was to give them the same prefix `schedjoules_fragment_event_details*` so that they can be found next to each other. Otherwise, it can be cumbersome to track down from code the layouts that are used by MicroFragments for the same screen.
The suffix didn't matter to me.
@dmfs Okay to keep the prefix?

**Comment by dmfs** [comment]
Yes, the prefix is fine.
