### ISSUE TITLE
Replace event detail icons with correct 24dp size versions and refactor layouts to use drawableLeft

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#191]
See https://github.com/schedjoules/android-event-discovery-sdk/pull/184#issuecomment-292927315

For icon naming from now, I suggest we keep the name from https://material.io/icons/, just add the schedjoules prefix. So we will see from name, the size and the color (white or black).

**Comment by lemonboston** [comment]
@wilfredstegeman , @dmfs 
When replacing the icons with new resources, I didn't find the one that we use for ADD TO CALENDAR - the calendar with that + sign, so I replaced that with this one
https://material.io/icons/#ic_event

![device-2017-04-24-154451](https://cloud.githubusercontent.com/assets/1077972/25340120/0988e526-2905-11e7-8c29-6fe1c9e58b5f.png)

Let me know if we should try to keep the original one, but if it's not a big issue, then I suggest we use icons from this official, standardized Material icon set whenever possible.
(That may change over time, for example I guess that + sign version has been removed)

**Comment by dmfs** [comment]
The calendar icon with the "+" in it, was hand crafted by me. I think the stock icon is fine too. Unless @wilfredstegeman has any objections we can keep it.

**Comment by wilfredstegeman** [comment]
The new one is fine.
