### ISSUE TITLE
Color tinted ProgressBar

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#192]
In order to reduce code duplication, improve code quality around setting tint color for ProgressBar in a background compatible way, as a developer I want a ProgressBar subclass that takes care of that automatically.

---

(Coming out from the review of https://github.com/schedjoules/android-event-discovery-sdk/pull/185)

This code
```
if (Build.VERSION.SDK_INT < 21)
        {
            // on older Version the progressbar won't pick up the accent color, so we have to set it manually
            mViews.schedjoulesEventListProgressBar.getIndeterminateDrawable()
                    .setColorFilter(getResources().getColor(R.color.schedjoules_colorAccent),
                            PorterDuff.Mode.MULTIPLY);
        }
``` 
can be improved to this:
```
DrawableCompat.setTint(DrawableCompat.wrap(views.schedjoulesEventDetailsHorizontalActionsProgressbar.getIndeterminateDrawable()),
                        ContextCompat.getColor(getContext(), R.color.schedjoules_colorAccent)
```
(API level check could be kept as well, to not do the tinting unnecessarily)
And applied in the ProgressBar subclass, which we can then reference in xml.

Hardcoding the color to accentColor is probably good enough.

**Comment by dmfs** [comment]
Make sure to use this progress bar in all places (also see #211)

**Comment by lemonboston** [comment]
See also https://github.com/schedjoules/android-event-discovery-sdk/pull/208#issuecomment-295753043
