### ISSUE TITLE
Upscroll fling stops at collapsed toolbar.

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#197]
When scrolling upwards on the details page with a fling gesture, the scroll stops abruptly on the collapsed toolbar. The expected behavior is that scrolling stops at the fully expanded toolbar.

This is probably an issue with the support library: https://code.google.com/p/android/issues/detail?id=183738

**Comment by wilfredstegeman** [comment]
This thread started 1,5 years ago. Decide on a different library or change the UX pattern?
