### ISSUE TITLE
Refactor details view

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#198]
To work around an issue with Android 4, we had to duplicate the details view (and a few other layouts). This approach is inconvenient, because all layout changes have to be made twice now. A better approach might be to include the shadow view and make it an empty View on Android 5+ like so
```xml
<View android:width="0dp" android:height="0dp" android:visibility="gone" />
```

**Comment by lemonboston** [comment]
This change is certainly something we need to make to help maintainability, but until categories are implemented, can we move it back to Backlog, to keep Spring Backlog focused?
