### ISSUE TITLE
Two line event header date-time touches title 

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#202]
![device-2017-04-12-203717](https://cloud.githubusercontent.com/assets/1077972/24973675/edbc1d02-1fbf-11e7-8c5e-2aa114c765c8.png)

**Comment by dmfs** [comment]
That's another reason why we should go for start date only.

**Comment by dmfs** [comment]
This should no longer be an issue with #205

**Comment by dmfs** [comment]
#205 has been merged, so this should be resolved. Reopen if you still see this.
