### ISSUE TITLE
Google Play services upgrade message

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#204]
This is how it looks like when you open the details view on a device with an outdated Google Play services app:

![device-2017-04-12-234658](https://cloud.githubusercontent.com/assets/1614987/24981135/8b17ccca-1fdb-11e7-8147-af9e35bbb213.png)

The problem: you can't press the button to update the app, because it launches Google Maps

**Comment by dmfs** [comment]
This should become obsolete when #207 has been implemented.

**Comment by lemonboston** [comment]
Just putting the note here that it was suggestion to use MapView inside our own Fragment: https://github.com/schedjoules/android-event-discovery-sdk/pull/215#pullrequestreview-33903042
