### ISSUE TITLE
Words are linkified incorrectly in event description

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#210]
![device-2017-04-18-170424](https://cloud.githubusercontent.com/assets/1077972/25137806/175e18de-2459-11e7-8d6f-e4b643ecca8d.png)

http://stackoverflow.com/questions/30528825/android-autolink-is-too-aggressive
http://stackoverflow.com/questions/43384870/text-with-dot-displayed-as-hyperlink

**Comment by dmfs** [comment]
On some devices this also applies to numbers. On my phone every number with at least 2 digits is linkified as a phone number, which is pretty annoying.

**Comment by dmfs** [comment]
What we need is custom link patterns: http://www.indelible.org/ink/android-linkify/
@wilfredstegeman which patterns should we linkify? Some of the options are

 * full URLs (i.e. "http://...")
 * host names (i.e. URLs with missing http or https scheme, like "example.com" or also "example.com/abc"). This is error prone and produces false positives as you can see above. One way to deal with that is to do this in two steps, first linkify without this and show the result, but also start a linkify background task that checks if the linked phrases refer to existing host names (i.e. do a DNS lookup) and replace the result when this has finished.
 * email addresses
 * phone numbers, we would need to apply certain constraints when we decide what's a phone number (like a minimal length of 5-8 digits or so).
 * twitter mentions (i.e. "@xxxx")

**Comment by lemonboston** [comment]
As a first iteration and improvement on this we could leave out the host names (web address without "http(s)://"), and also phone numbers and twitter from the list above. So basically linkify only full URLs and email addresses. To keep it simpler and make a step forward.
 
@dmfs @wilfredstegeman What do you think?

Then we could create separate tasks for each of the other cases if needed.

**Comment by dmfs** [comment]
@lemonboston yes that's exactly what we should do, start with the easy ones.
