### ISSUE TITLE
Event list loading indicator circling item is white instead of green

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#211]
Or is that deliberate?

![device-2017-04-18-202857](https://cloud.githubusercontent.com/assets/1077972/25146867/cb8bc5c4-2475-11e7-9225-c118c97701f6.png)

**Comment by dmfs** [comment]
I guess I missed that one during the changes on the list. It should be fixed in the scope of #192.

**Comment by dmfs** [comment]
I'm closing this, because it's subject to #192 (and also mentioned there).
