### ISSUE TITLE
Location search input clearing 'X' button is invisible on new white theme

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#217]

**Comment by lemonboston** [comment]
TODO As part of this, replace png icon with vector drawable and apply the tint based on theme.
(In #191, I am replacing all icons with vector drawables except this one.)

**Comment by dmfs** [comment]
Why not replace this one in #191 too?

**Comment by lemonboston** [comment]
The current png is white but the vector drawables I use now are black*, so if I replace the icon, the title of this bug won't be valid any more :) - there will be a full black 'X' on both the light and dark theme. So I would do this together with the tinting, but that's better to do after theme refactor is merged, to use attribute.

*Any material icon can be added as Vector Asset directly from Android Studio and it uses black by default.
