### ISSUE TITLE
Show sale status information on ticket button

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#221]
In order to have my expectations manged properly, as a user I don't want to see a ticket button if there are no tickets available.

**Comment by lemonboston** [comment]
I missed what was this exactly about, could someone remind me please?
Currently we don't show the ticket button if there is no `http://schedjoules.com/rel/action/book` action link with `http://schedjoules.com/booking/type` as `ticket`. (If button was shown when this was not present, then that's a bug.)
Or is this about expired tickets? Is there a parameter for that that we should use?
Thanks.

**Comment by lemonboston** [comment]
@aramvisser Could you please remind us about this? What is that case when there is _book_ action link with _ticket_ subtype, but in fact no ticket available for the event - what is the extra parameter we need to check for?

**Comment by rutgerg** [comment]
There is a sale-status attribute in actions. It currently has 6 options : unknown, available, unavailable, unlimited, multiple, donation. You are looking for unavailable I guess.

A better option imo than to remove the button is to show a button that says 'no tickets'. That could still be clickable.

**Comment by lemonboston** [comment]
Thanks, I see the `sale-status` attribute:

```json
 "links": [
     {
         "rel": "http:\/\/schedjoules.com\/rel\/action\/book",
         "href": "https:\/\/actions.schedjoules.com\/actions\/85cf7098d8e97543",
         "properties": {
             "http:\/\/schedjoules.com\/props\/booking\/type": "ticket",
             "http:\/\/schedjoules.com\/props\/booking\/price-min": 8.51,
             "http:\/\/schedjoules.com\/props\/booking\/price-max": 8.51,
             "http:\/\/schedjoules.com\/props\/booking\/currency": "EUR",
             "http:\/\/schedjoules.com\/props\/booking\/sale-start": "2017-02-03T10:00:00Z",
             "http:\/\/schedjoules.com\/props\/booking\/sale-end": "2017-05-06T06:00:00Z",
             "http:\/\/schedjoules.com\/props\/booking\/sale-status": "unavailable",
             "http:\/\/schedjoules.com\/props\/vendor\/icon": "data:image\/png;base64,XXXXXXXXX"
         }
     },
     {
         "rel": "http:\/\/schedjoules.com\/rel\/action\/add-to-calendar"
     },
     {
         "rel": "http:\/\/schedjoules.com\/rel\/action\/share",
         "href": "https:\/\/actions.schedjoules.com\/actions\/92eaeb6c7b7d7b63"
     },
     {
         "rel": "http:\/\/schedjoules.com\/rel\/action\/directions",
         "href": "https:\/\/actions.schedjoules.com\/actions\/c716658e908fedd1"
     }
 ]
}
```

So I suppose we should then discuss what to do when it's 'unavailable'... I'll post it in Slack.

**Comment by lemonboston** [comment]
As agreed on the call we will change the text on the ticket button based on the sale statuses.
We will need to find good phrases.

**Comment by dmfs** [comment]
As discussed during the call, we're just going to relabel the button if no tickets are available. I propose to change the text to "No tickets available" and change the background color to some shade of grey.

**Comment by lemonboston** [comment]
Dumping here Aram's note from Slack about the statuses and their meanings:

> I can expand a bit on the the different ticket statuses in the way it's implemented now:
> - unknown: Ticket status is unknown
> - available: Tickets are available
> - unavailable: No tickets are available, reason is not known (sold out, not being sold yet)
> - unlimited: No ticket necessary to purchase
> - multiple: This ticket represents a combination of multiple tickets, only min_price and max_price are useful, status of each indiviual ticket and how many tiers there are is unkown
> - donation: Entrance requires a minimum donation. The minimum donation is usually mentioned in the description

**Comment by lemonboston** [comment]
This is how the button looks like with "No tickets available" and `#bdbdbd` grey background:
![device-2017-05-15-175542](https://cloud.githubusercontent.com/assets/1077972/26066618/bf141b84-3997-11e7-8cfb-a7a181ecd92e.png)

Feel free to suggest anything. If label is fine, @wilfredstegeman , @dmfs can you please provide Dutch and German translations?

**Comment by lemonboston** [comment]
Dark theme sample:
![device-2017-05-15-180900](https://cloud.githubusercontent.com/assets/1077972/26067199/9d376668-3999-11e7-8a82-b09e8b5f6565.png)

**Comment by dmfs** [comment]
The German version is "Keine Tickets verfügbar".

The grey in the dark version should be darker.

**Comment by wilfredstegeman** [comment]
The Dutch version is "Geen tickets beschikbaar".

**Comment by dmfs** [comment]
Rebase on master and make sure the button shows the first ticket which is available, if any.
