### ISSUE TITLE
Let capitalization be applied by style

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#224]
Currently we hard code upper case conversion for some of the labels. This, however, should be left to the style of the element using [textAllCaps](https://developer.android.com/reference/android/widget/TextView.html#attr_android:textAllCaps) if it's not applied by default (like for buttons).

**Comment by lemonboston** [comment]
Doing this as part of #194 (Directions will get a dedicated layout there, so the need for customizing caps from code ceases.)

**Comment by lemonboston** [comment]
This was implemented in #194, closing it.
