### ISSUE TITLE
Event loading error screen is not nice

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#246]
On a Karbonn Sparkle V device when there is no internet and trying to load event by uid:

![device-2017-05-03-192010](https://cloud.githubusercontent.com/assets/1077972/25672838/9eece8d8-3035-11e7-92b2-02aba3009e6b.png)

@dmfs Please prioritized this if needed.

**Comment by dmfs** [comment]
as far as it concerns me, this is low prio. We'll fix this during one of the upcoming sprints.
