### ISSUE TITLE
Category Provider

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#255]
In order to resolve category labels easily, as a developer I want a `ContentProvider` which resolves category names.
---

The advantage of a content provider is that it works stateless, i.e. you don't need to connect and disconnect like with a service. We should provide sufficient tools to resolve category names easily. Not sure if we can get something like this to work easily:

```
Optional<CharSequence> categoryLabel = new CategoryLabel(context, categoryLink.href());
```

The label is optional, because the category label could be unknown at the time it it resolved, either because the initial request didn't finish yet or a connection issue occurred or simply because the category is merely internal and has no label.

Instead of passing the href of the link object we could use a dedicated `Category` model and pass that one. I'll consider this in schedjoules/java-api-client#31.

This could allow to iterate category names like this:

```
for (CharSequence label : new Labeled(context, new Categories(event.links())))
{
   // show label
}
```

**Comment by lemonboston** [comment]
As per the current plan we won't need Content Provider, so I am closing this.
