### ISSUE TITLE
Event discovery menu item not always visible in CalenGoo

### ISSUE THREAD

**Issue by wilfredstegeman** [schedjoules/android-event-discovery-sdk#265]
Dominique just sent me an email regarding the availability of the event discovery in the menu of CalenGoo. Note: CalenGoo uses version 1.3.1 of the SDK in the production app.

Dominique said the following:

Hmm, it doesn't appear in the menu any more....
After installing a new version it now appears again. Is the check if it is available maybe sometimes unreliable? I sometimes saw errors in the log when connecting to your servers. Have you heard about such problems?

I have tested it now again with the release version. The menu is gone again. The error is

```
16.05.2017 17:45:58: java.util.concurrent.TimeoutException
at com.schedjoules.eventdiscovery.framework.h.e.b(FutureLocalServiceConnection.java:118)
at com.schedjoules.eventdiscovery.service.a$a.a(ApiService.java:78)
at com.calengoo.android.controller.i$1.run(EventDiscoveryWrapper.java:39)
at java.lang.Thread.run(Thread.java:761)

```
Have you heard about this error? The code is

```
ApiService.FutureConnection apiConnection = new ApiService.FutureConnection(context);
try {
    ApiService apiService = apiConnection.service(1000);
    // build the coverage api query
    FluentCoverage coverageQuery = new Coverage(Locale.getDefault());

    Optional<Token> networkCountry = new NetworkCountryCode(context);
    if (networkCountry.isPresent()) {
        coverageQuery = coverageQuery.withOperatorCountry(networkCountry.value());
    }

    eventDiscoveryAvailableInThisCountry = apiService.apiResponse(coverageQuery);
} catch (IOException | ProtocolError | URISyntaxException | TimeoutException | InterruptedException | ProtocolException e) {
    e.printStackTrace();
    LogMem.add(e);
} finally {
    apiConnection.disconnect();
}

```
So it seems despite it was activated some/many users don't even see the menu. I think I took the code from one of your examples. Maybe the timeout 1000 is too small?

**Comment by rutgerg** [comment]
It depends on what he sends. I don't see that in the code.

Is 1000 in ms? That should be more than enough

**Comment by wilfredstegeman** [comment]
He says he took the code from one of our examples. Does the example say if it should be 1000 and that it should be ms, something else or no metric unit at all?

**Comment by dmfs** [comment]
`1000` is ms to connect to the local API service (this is a local proxy to the actual API). 1000 ms should be more than enough to connect to a service that runs on the device. There must be another reason.

First of all, our code falls back to the most recent result if something fails for any reason: https://github.com/schedjoules/android-event-discovery-sdk/blob/master/eventdiscovery-sdk/src/main/java/com/schedjoules/eventdiscovery/framework/services/CoverageService.java#L114

He probably should start by adding this mechanism.

Maybe he starts the check more than once in a short time? That could result in such an error.

**Comment by wilfredstegeman** [comment]
@dmfs can you get in touch with Dominique about this?

**Comment by dmfs** [comment]
Done

**Comment by dmfs** [comment]
He said that the problem doesn't appear with a timeout of 5000 ms. Apparently his app is so busy during the first launch that the start of the ApiService takes more than 1s. On subsequent launches (when the ApiService is already running in the background) the problem is non-existent.

Just to be sure we should set the timeout to 5000 ms in our code as well.
