### ISSUE TITLE
Scrolling fast to bottom of event list sometimes hit the end without showing loading indicator

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#27]
.. but then scrolling again down shows the indicator.
I could consistently reproduce it with Rotterdam.

(This is relevant only after #19 is merged.)

**Comment by dmfs** [comment]
At present this doesn't looks like a real issue. It only happens when scrolling really fast and even then it doesn't happen every time. Closing this.
