### ISSUE TITLE
Create OptionalBox<T> class

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#271]
In order to be able to serialize `Optional<T>` types easily without code repetition, as a developer I want to have a general `OptionalBox<T>` class.
---

It probably cannot be solved without creating some kind of factory for the actual `Box<T>` class.

Here is what I had in mind after some thought:

```java
interface BoxFactory<T> extends Parcelable
{
   Box<T> create(T value);
}

class OptionalBox<T> implements Box<Optional<T>>
{
     OptionalBox(Optional<T> optValue, BoxFactory<T> boxFactory)
    {
       ....
    }

    .....
}

class DateTimeBox implements Box<DateTime>
{
    ....

   static class Factory extends AbstractStatelessParcelable
   {
        @Override
        Box<DateTime> create(DateTime value)
       {
              return new DateTimeBox(value);
       }
       
      CREATOR..
   }

}

Box<Optional<DateTime>> box = new OptionalBox<>(optDateTime, new DateTimeBox.Factory());

```

edit: corrected OptionalFactory to OptionalBox

**Comment by dmfs** [comment]
How about a custom `Boxable<Optional<DateTime>>` adapter?

i.e. 
```java
public final class OptionalDateTimeBoxable implements Boxable<Optional<DateTime>>
{
  ...
}
```

To be used like this:

```java
Box<Optional<DateTime>> box = new OptionalDateTimeBoxable<>(optDateTime).boxed();
```

The name is a bit longish though.

**Comment by lemonboston** [comment]
Right, that's probably less code to implement than that factory since it doesn't need to implement `Parcelable`.

Maybe having that as inner class, to be able to write something like this:
```
Box<Optional<DateTime>> box = new DateTimeBox.Opt(optDateTime).boxed();
```

**Comment by dmfs** [comment]
Inner class, good one.

**Comment by lemonboston** [comment]
Since that custom (inner) class has to be added for each type and no general type needs to be created with that proposal, this is no longer a task. We can add those custom classes on demand.
I am closing this.

**Comment by lemonboston** [comment]
I need to do this as part #298 and during implementing it looks like for me that the factory option would look better after all.
This is how that `Boxable` inner class look like:

```java
public final static class Opt implements Boxable<Optional<Event>>
    {
        private final Optional<Event> mOptEvent;


        public Opt(Optional<Event> optEvent)
        {
            mOptEvent = optEvent;
        }


        @Override
        public Box<Optional<Event>> boxed()
        {
            return mOptEvent.isPresent() ? new PresentBox<>(new EventBox(mOptEvent.value())) : new AbsentBox<Event>();
        }

    }
```
It's not bad but as we need to write this for each `Box` we use with `Optional`, we would probably copy-paste from an existing one and re-write...     so somehow the factory looks better, basically that's just a function to create the `Box` from `T`, contains no logic. It might work better with collection `Box`-s as well, that we can pass that as ctor param. Like `new IterableBox<T>(iterableT, boxFactoryT)`.
