### ISSUE TITLE
Don't reload event list when coming back from event details

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#273]
This is a known intermediary issue during the refactoring that prepares the structures for the categories.
It is separated to a task to avoid other pull request growing too big.

**Comment by lemonboston** [comment]
Fixed on branch `categories/273-dont-reload-list-from-details`, will submit PR after #72 is merged to `categories/master`.

**Comment by lemonboston** [comment]
The lifecycles we talked about:

Normal Fragment:
1.. First initialization
onCreate(), onCreateView(), savedState=null
2.. Rotation
new Fragment instance, onCreate(), onCreateView(), savedState!=null
3.. Popped from backstack
same Fragment instance, onCreateView(), savedState=null

Retained Fragment (1 and 3 are the same):
2.. Rotation
same Fragment instance, onCreateView(), savedState!=null

I will update the code shortly with what I have in mind to handle case 3.

**Comment by lemonboston** [comment]
When normal fragment is on backstack while rotating the screen:
immediately recreated: new Fragment instance, onCreate(), savedState!=null
when popping back from back stack: same Fragment instance, onCreateView(), savedState!=null

Logs:
```
05-19 14:47:48.402 D/Investigator: [main] EventDetailFragment{e41335f #2 id=0x7f0d0009}.onCreate() | savedState = null
05-19 14:47:48.403 D/Investigator: [main] EventDetailFragment{e41335f #2 id=0x7f0d0009}.onCreateView() | savedState = null

// Rotation while note having EventDetailFragment on screen (on Feedback)
05-19 14:48:12.807 D/Investigator: [main] EventListFragment{7a05c9c #0 id=0x7f0d0009}.onCreate() | savedState = Bundle[{android:support:fragments=android.suppo....
05-19 14:48:12.815 D/Investigator: [main] EventDetailFragment{321c607 #2 id=0x7f0d0009}.onCreate() | savedState = Bundle[{android:suppo....

// Back to event details
05-19 14:48:27.670 D/Investigator: [main] EventDetailFragment{321c607 #2 id=0x7f0d0009}.onCreateView() | savedState = Bundle[{android:support:fragments=android.sup.....
```

**Comment by lemonboston** [comment]
I vote for 5 story points for this, because of the effort involved to investigate, log and collect those lifeycycle scenarios and the discussion.
Could be 3 as well if you see that more fit.

**Comment by dmfs** [comment]
ok, let's go with 5
