### ISSUE TITLE
eventlist disappears during transition to details view (categories branch)

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#280]

**Comment by lemonboston** [comment]
@dmfs This is coverd by https://github.com/schedjoules/android-event-discovery-sdk/issues/281, isn't it? Can we close this one?

**Comment by dmfs** [comment]
I don't think so. It's not about the transition. The problem is the previous fragment disappears when the transition starts. Might be a MF bug.

**Comment by dmfs** [comment]
Interestingly, the details screen is not removed during the back transition, except for the map view. Is it possible that this affects nested fragments? So are nested fragments removed when a fragment transition is started for the parent fragment?

**Comment by lemonboston** [comment]
Good guess, it seems so:
https://stackoverflow.com/questions/14900738/nested-fragments-disappear-during-transition-animation

**Comment by dmfs** [comment]
I think setting the background fragment might make this less urgent, especially with the bottom-up transition in place, because it will be less apparent that the nested fragments disappear.

Anyway, it looks like there is a reasonable workaround.

**Comment by lemonboston** [comment]
The task about the backgrounds is #320.
Moving this back to Backlog for now.
