### ISSUE TITLE
Upgrade to MicroFragments 0.2.1

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#299]
MF 0.2.1 fixes a crash when being used with support library >= 25.1.0

**Comment by lemonboston** [comment]
Was that the only change in MF 0.2 -> 0.2.1 ?
I see a big commit in the history: aa52c346c7be35b207b8619924ee049e52516cae

I am asking it to know if we can do this simply on master or should we wait for merging other pull request in line.

**Comment by lemonboston** [comment]
Oh, never mind, I see we use that commit now and not 0.2.1, so it's safe to update. I will do this.
