### ISSUE TITLE
Event list top date header glitch upon loading previous page

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#3]
@lemonboston commented on [Thu Dec 01 2016](https://github.com/schedjoules/android-event-discovery-sdk-int/issues/52)

The topmost date header item, if the list is pulled to top, turns white when new items are added above it (previous page is loaded). 
When scrolling down after that, the header is not shown.

It's a bug in the FlexibleAdapter library we use for the sticky headers.

- [x] When this bug has been fixed, re-enable automatic previous page loading upon screen load (just uncommenting a line)

---

@lemonboston commented on [Thu Dec 01 2016](https://github.com/schedjoules/android-event-discovery-sdk-int/issues/52#issuecomment-264235640)

A tip from Marten was to try replacing the whole RecyclerView.Adapter with a new instance upon loading the new items, and scrolling to the last position.
(Positions are nicely kept automatically now without any code, so it would add complexity.)

---

@lemonboston commented on [Thu Dec 01 2016](https://github.com/schedjoules/android-event-discovery-sdk-int/issues/52#issuecomment-264236301)

This was in the log when these happened, not sure if it's related though:
```
12-01 11:36:44.645 W/View: requestLayout() improperly called by android.widget.FrameLayout{aa55ef1 V.E...... ......ID 0,0-1080,95} during layout: running second layout pass
```

**Comment by lemonboston** [comment]
Created bug on FlexibleAdapter github page:
https://github.com/davideas/FlexibleAdapter/issues/244

**Comment by dmfs** [comment]
This fixes it when loading the initial page and its previous page. However, if I quickly scroll up to the top (with a city selected that has no events today) I still see it when the final previous page is loaded. I think it happens when the "no events" item is inserted.

**Comment by lemonboston** [comment]
I am working on adding the progress items instead of the overlay, that might affect that case you described, too. Could we merge this and create a separate bug for that? So I could branch off from this.
This one at least fixes the initial loading and maybe the progress items will fix that case as well.
