### ISSUE TITLE
In order to filter by event location, as a user I want a decent location picker.

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#30]
The location picker should offer various options like

* current location
* recent locations
* top cities in my country
* home location (from profile)

**Comment by lemonboston** [comment]
Just dumping a note here:
We could make nearby locations prioritized in the suggestions by setting a location bias on the query to the Google API:
https://developers.google.com/android/reference/com/google/android/gms/location/places/GeoDataApi.html#getAutocompletePredictions(com.google.android.gms.common.api.GoogleApiClient, java.lang.String, com.google.android.gms.maps.model.LatLngBounds, com.google.android.gms.location.places.AutocompleteFilter)

Worth trying out once we have current location available.
