### ISSUE TITLE
Create CategoryService

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#303]
For the categories support, as a developer, I want to have a proper solution for loading and caching the category labels.
---

As we discussed the simplest approach is probably to do the same as with `ActionService`.
So this is the proposal for `CategoryService`:

```java
public interface CategoryService
{
    Optional<Category> category(Uri categoryId);

    Optional<Category> cachedCategory(Uri categoryId) throws NoSuchElementException;
}
```

Absent return value would mean we don't have a label for that category which should not really happen, so I am not sure actually if we should handle that or not. In that case we can refetch the categories from the API and that should contain that. But what if we have a network error there during that refetch call and otherwise we could just omit displaying it.
In general I think it's preferable not to handle errors which should not happen, but I am not sure about this case.
@dmfs what do you think?

**Comment by lemonboston** [comment]
Thinking about it more, I think we shouldn't handle that case when we couldn't get a label. We should treat that as any other error. The SDK is fully dependent on network communication now, we don't have offline mode, so not being able to fetch categories is the same as any other failed calls, we show the appropriate error screen.
Otherwise we increase complexity in UI/UX and application logic if we start to design for cases which should not happen.
So I say we should always be able to resolve category labels (if needed by refetching them from the API within those background method calls).

So the proposed interface:
```java
public interface CategoryService
{
    Category category(Uri categoryId) throws TimeoutException, InterruptedException, ProtocolError, IOException, ProtocolException, URISyntaxException;

    Category cachedCategory(Uri categoryId) throws NoSuchElementException;
}
```

**Comment by dmfs** [comment]
what's the difference between these two methods?

**Comment by lemonboston** [comment]
(added `throws` clause to `category()` method above)

`cachedCategory()` only serves from cache and throws `NoSuchElementException` if not found, `category()` fetches from API if not found in the cache.

The signature of `cachedCategory()` is for practical purposes after checking how `ActionService` is used:
```java
try
            {
                List<Link> actions = actionService.service(40).cachedActions(mEvent.uid());
                nestedBundle.putParcelable("MicroFragment", new ShowEventMicroFragment(mEvent, actions));
            }
            catch (InterruptedException | TimeoutException | NoSuchElementException e)
            {
                nestedBundle.putParcelable("MicroFragment", new ActionLoaderMicroFragment(mEvent));
            }
```
So that `TimeoutException` has to be handled anyway, so the cache method throws as well, so both cases end up in catch clause.
Alternative could be to have `Optional` return value and no `NoSuchElementException`.

**Comment by lemonboston** [comment]
A general note for this: so as I see we can reduce much complexity with the MF approach of separating loading screens from showing screens, but it has little drawback here: if we don't want to flash up the loading screen when serving from cache, we need to have separate methods to check them. So normally this would be transparent, we wouldn't care in the presentation layer where the data is loaded from, from cache or network, we would display loading animation in the meantime. But with MF loading fragments we need to route now based on that.

**Comment by dmfs** [comment]
how about a method which allows the caller to indicate he's willing to wait?

```java
// returns an absent value if the category is not fetched and quickReturn is true
Optional<Category> category(Uri categoryId, boolean quickReturn) throws TimeoutException, InterruptedException, ProtocolError, IOException, ProtocolException, URISyntaxException;
```

Or return a `Future<Category>` instead

```java
Future<Category> category(Uri categoryId);
```

When running on the UI thread you would get it like so

```java
// throws TimeoutException if category is not cached
Category cat = category(Uri categoryId).get(2, TimeUnit.MILLISECONDS);
```
The drawback is that the Future would throw a very generic `ExecutionException` if there is any network or protocol error. But I'm not sure if that would be a problem.

We probably should use the same method for actions then.

I don't see how MFs make this more complicated. Would you always show a loader animation when not using MFs? You can just do the same with MF. You don't have to check beforehand.
Checking beforehand is just an optimization to avoid the loading screen if we have everything in the cache.

**Comment by lemonboston** [comment]
I think the way we are using these Services now with FutureServiceConnection or the JobQueues doesn't allow to use them on UI thread because of the `service(timeout)` call first. So even thought we may want to reach an in-memory cache which could be instant, since we do that with a Service, we need to do it from background.

About the comment line here:
```java
// returns an absent value if the category is not fetched and quickReturn is true
Optional<Category> category(Uri categoryId, boolean quickReturn) throws TimeoutException, InterruptedException, ProtocolError, IOException, ProtocolException, URISyntaxException;
```
We need to be able to distinguish between no-cache or not-found-in-cache, because we may need to launch a loader MF to fetch the categories if they are not fetched already. Like when launching details screen by uid.
The absent return value would mean both thing. 

So I see this option now:
```java
interface CategoryLabelService
{
    Optional<Category> category(Uri categoryId) throws NetworkExceptions;
    Optional<Category> cachedCategory(Uri categoryId) throws NoCacheException;
    // optionally this as well:
    boolean isCacheInitialized();
}
```

Or, I actually started to use something like this:
```java
public interface Categories extends Iterable<Category>
{
    Optional<Category> category(Uri categoryName);
}
```
To hide the actual Map. So we may use this as well on the Service interface like
```java
interface CategoryLabelService2
{
     Optional<Categories> cachedCategories();
     Categories fethCategories() throws NetworkExceptions;
}
```
(This looks better for me)
(If you think about `Category c = new Category(categoryId, iterableCategory)` it wouldn't be efficient to always iterate through, so I think we need to offer the lookup method somewhere and hide the Map below in any case)

I will implement it in some way (it's mostly done already) so we can also continue with this in actual code review, may be easier.

However, until we don't merge the preparation-refactor PRs to categories/master and then master, we can't add this to that, so it will probably live a bit on a parallel branch, so I won't submit a PR yet.

**Comment by lemonboston** [comment]
About the MFs and load routing - you're right it's not directly about MFs, we could do the always show loading with MFs as well. MFs just make it easier to implement what is actually right, which is to not show loading, but it comes with routing logic about cache state.

**Comment by lemonboston** [comment]
A preliminary version is now on `demo/category-on-details` branch, the Service is not wired in for use yet, since that will be a separate task. (other changes on the branch are not relevant for this story)
I leave it now until we can make a PR from this.

**Comment by lemonboston** [comment]
Since we are using `ViewModel` to hold the cache, we don't need this anywmore. Closing it.
