### ISSUE TITLE
In order to see events at my current location quickly, as a user I want it to open the event discovery at my current location

### ISSUE THREAD

**Issue by rutgerg** [schedjoules/android-event-discovery-sdk#310]
@rutgerg commented on [Mon Jan 30 2017](https://github.com/schedjoules/backlog/issues/126)

**Comment by lemonboston** [comment]
Moving this back to backlog as it's not related to categories which we focus on now.

**Comment by dmfs** [comment]
Now with the initial loader in place we should get back to this. The initial location could be determined during the loader based on:

* Current location if known and permission has been granted
* Geo IP otherwise

Other options?
