### ISSUE TITLE
(Categories branch) Duplicate location header on top of each other

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#315]
See: https://github.com/schedjoules/android-event-discovery-sdk/pull/286#issuecomment-310344510

One way to reproduce:
1. Open discovery list
2. Open an event details, rotate, rotate back, go back to list
3. Open location selection and select a different city
Result: both locations displayed on top of each other (see screenshot above)

**Comment by wilfredstegeman** [comment]
I don't have this issue.

**Comment by lemonboston** [comment]
It's only in a development branch, caused by recent changes, so this is not in any release and it will be fixed before it would get there. Marten created the labels `bug` and `live-bug` to distinguish between not-released and released bugs, I try to use them appropriately.
