### ISSUE TITLE
Google maps always shows 'Unnamed location'

### ISSUE THREAD

**Issue by wilfredstegeman** [schedjoules/android-event-discovery-sdk#321]
![screenshot_2017-06-29-10-09-59](https://user-images.githubusercontent.com/5968782/27682839-4be186b0-5cc4-11e7-9fbb-b5d995065f11.png)
![screenshot_2017-06-29-10-10-21](https://user-images.githubusercontent.com/5968782/27682841-4be5ab5a-5cc4-11e7-8f0c-bf6f485239c3.png)
![screenshot_2017-06-29-10-10-27](https://user-images.githubusercontent.com/5968782/27682840-4be46be6-5cc4-11e7-8b7e-06819a3ff8a3.png)

**Comment by dmfs** [comment]
This should be resolved when we don't use the action API to open the map, but create the intent locally.

**Comment by wilfredstegeman** [comment]
Have we planned this already or you just mean that that's the solution to this issue?

**Comment by dmfs** [comment]
both
