### ISSUE TITLE
Location picker: cursor starts in text box with keyboard hidden 

### ISSUE THREAD

**Issue by wilfredstegeman** [schedjoules/android-event-discovery-sdk#322]
Because the cursors is already in the text box, but the keyboard is hidden, it feels strange to tap the text box again.

There are two options imo:

1. don't start with the cursor in the text box and hide the keyboard > this way I know I have to click the textbox to show the keyboard
2. start with the cursor in the text box and show the keyboard > this way I can start typing immediately

I personally prefer the second option.

**Comment by dmfs** [comment]
IMO the first option makes more sense. In most cases you probably just click "current location".
Also (after using it for some time) there is a good chance your location is already in the "recent locations" or some other block we might show in future releases (like "Popular locations", "Upcoming trips locations", "Home & work location").
If the keyboard opens up there is much less room for the recent locations and other such blocks, though.

**Comment by wilfredstegeman** [comment]
When we choose option 1 we should add a magnifying glass to the search field imo, otherwise it looks like a static title bar. 

Example
![image uploaded from ios 10](https://user-images.githubusercontent.com/5968782/27686250-4355b328-5cd2-11e7-83bd-7f87b7bfce01.jpg)

**Comment by dmfs** [comment]
agreed, a search icon is mandatory just like a hint text "search location"

**Comment by wilfredstegeman** [comment]
Agreed. That's an improvement over 'Enter location'. And while we're discussing the location picker. On all my devices, the location in the header is very insensitive. Most of the times I have to press the location in the header multiple times before the location search screen opens. Do you have the same?

**Comment by dmfs** [comment]
for me it works every time. Maybe the hot area is too small and you happen to hit the edges?

**Comment by wilfredstegeman** [comment]
It doesn't really matter where I touch it, right on top of it or on the side, it almost always happens, and on all different devices as well.

**Comment by lemonboston** [comment]
This happened to me as well multiple times, so I've created a bug now: https://github.com/schedjoules/android-event-discovery-sdk/issues/323
Should this be addressed now, before categories?

**Comment by wilfredstegeman** [comment]
Is it a matter of enlarging the hot area?

**Comment by dmfs** [comment]
doesn't sound like so. I'll publish a new alpha with plenty of changes under the hood today, let's see if the problem still persists.
