### ISSUE TITLE
Test low memory (Activity killed, process death) scenarios

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#330]
In order to ensure correct working of the SDK, or at the minimum not crashing, in the rare scenarios when the system kills part or the whole app to save resources, as a developer I want a reliable way to test these.
---

The 2 methods usually suggested to test this - "Don't keep Activities", and kill the process in Android Studio - don't seem to work as expected for some reason, so we need to look into this more.

**Comment by lemonboston** [comment]
TODO as part of this, check how categories cache is accessed after restoration.

**Comment by lemonboston** [comment]
@dmfs I haven't been able to test it so far, if you have any ideas, suggestions please let me know.

These are the things I tried:

- Use "Don't keep Activities" phone debug option -> `MicroFragmentHostActivity` is not destroyed when I go to `LocationPickerActivity` or even outside the app with the Share button
- Kill the app from Android Studio with "Terminate Application" button while the app is in background, and then relaunch the app from recent apps -> the app starts with `MainActivity` instead of trying to restore `MicroFragmentHostActivity` with its `Fragment`s as multiple blog posts say it should be doing
- Use following adb commands to trigger low memory simulation: -> nothing happens, app stays intact
```
adb shell am send-trim-memory com.schedjoules.eventdiscovery.demo MODERATE
adb shell am send-trim-memory com.schedjoules.eventdiscovery.demo RUNNING_CRITICAL
```

-  I thought maybe the system is so smart that it knows about the retained Fragment and that alters the behvaiour, so I change it to non-retained -> nothing changed, the same behavior as above

It would be important to test this at this point because there is a good chance of a crash now when restoring the Activity and trying to reach the presumably emtpy `CategoriesCache`.
Not sure if it makes sense to try to fix that 'blindly' without actually seeing a crash.

**Comment by lemonboston** [comment]
- also tried to launch `LocationPickerActivity` not as `startActivityForResult` but with `startActivity` so that maybe that's what kept the `MicroFragmentHostActivity` live, but this didn't change anything either

**Comment by lemonboston** [comment]
This was all done on Nexus 5 device, but now I tried on API 22 Emulator, the same behavior.

**Comment by lemonboston** [comment]
I haven't been able to test it so far, so in order to move forward, I've applied a 'blind' fix for this by saving the cache to `savedInstanceState` in #340. 
I keep this ticket open but move it back to Backlog for now.

**Comment by lemonboston** [comment]
See this comment as well: https://github.com/schedjoules/android-event-discovery-sdk/issues/344#issuecomment-316638794

**Comment by IgorGanapolsky** [comment]
`am send-trim-memory` didn't solve your issue?
