### ISSUE TITLE
Create category filter UI bar

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#341]
Create the filter drop-down widget with only the categories, so no date or settings, and categories are just hardcoded dummies.
Widget is interactive, so drops down on tap, highlights selected items, collapses on tap on the header again, has a CLEAR item for clearing.
When dropping down, it is either an overlay on the list or pushes it down, whichever looks easier.

---

(Personal note: I think pushing the list down, so that filter can be left open and every change in it triggers reload of the list below without the need to close the filter could be a nice, interactive UX. Given that expanded filter doesn't cover the whole screen.)

**Comment by wilfredstegeman** [comment]
The most common filter is an overlay on the list when dropping down, which lso has my preference. The option of direct filtering of the results is indeed a nice interactive UX. Can you also achieve that with an overlay? And to have this effect also with more content in the dropdown we could maximize the size of the overlay, so you have to scroll through the results?

**Comment by dmfs** [comment]
In general I think an overlay is the more intuitive and simpler solution. We can certainly implement interactive UX with instant updates using the overlay pattern as well.

That being said, I can imagine using a push-down solution in combination with the quick-return pattern (see https://www.youtube.com/watch?v=PL9s0IJ9oiI). So when you expand the filter, it will scroll out of the view when you scroll down but it will reappear instantly when you scroll up again.

In general I think the quick filter should list only the most common or most frequently used options. If you need more there should be an "advanced filtering" button which presents you with the full list.

**Comment by lemonboston** [comment]
Right, I didn't realize that we would need quick-return as well for the push-down, otherwise we need to scroll to the top to see the filter. (A simpler vid about quick-return: https://www.youtube.com/watch?v=BwLjMMIWNQU)
This would probably complicate the solution so I will aim for the overlay first as you guys suggest. 

Updating the list on each category tap or only when filter is collapsed is probably not a big difference, I will see.

**Comment by lemonboston** [comment]
@wilfredstegeman @dmfs Could you please provide NL, DE translations for "Category" for the filter title?

**Comment by wilfredstegeman** [comment]
NL: Categorie
________________________________

**Comment by dmfs** [comment]
DE: Kategorie

**Comment by lemonboston** [comment]
Thanks, we also need to translate "CLEAR" which is the bottom item on the drop-down filter to clear and collapse the filter.
The mockup:
https://projects.invisionapp.com/d/main#/console/10528802/228235134/preview#project_console

Could you please provide NL, DE versions?

**Comment by wilfredstegeman** [comment]
We can also choose to not add a Clear option. It's a shortcut to uncheck
all options at once, which is also achieved by unchecking the checked
options. With only 5 categories in place, that's not so hard.

**Comment by wilfredstegeman** [comment]
NL: Herstel

**Comment by dmfs** [comment]
DE: Filter löschen
