### ISSUE TITLE
Replace Mapped(Optional) class of SDK with optional lib's Mapped(Optional)

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#351]
Use `org.dmfs.optional.decorators.Mapped` instead of `com.schedjoules.eventdiscovery.framework.utils.optionals.Mapped` and remove it.

**Comment by dmfs** [comment]
optional 0.4 has just been released

**Comment by dmfs** [comment]
Optional 0.5 is available now

**Comment by lemonboston** [comment]
If latest `optional` uses newer `iterators` as well, then TODO replace `EmptyIterator` from that.
