### ISSUE TITLE
Reduce complexity of ApiService code

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#355]
The ApiService code is quite verbose and mostly the same for all partners. It could be reduced to something like this:

```java
return new SdkApi(context, new StringAccessToken("0443a55244bb2b6224fd48e0416f0d9c"));
```
Information in `VersionedProduct` could be loaded automatically from the manifest.

**Comment by lemonboston** [comment]
Just an obvious not-to-forget note that the wiki needs to updated, too, when this is closed.
