### ISSUE TITLE
Description sometimes missing on details view

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#366]
I can't spot a pattern yet, but in some cases the description of events are missing when the same event on a different day has a description (so I'm pretty sure it's not an API issue).

This is probably a result of #345.

**Comment by lemonboston** [comment]
If we can add any concrete case here that could help figuring it out.

**Comment by dmfs** [comment]
I just had the same problem again. Here is what I did:

* Search events in Dresden
* (open a couple of events, not sure if that matters)
* scroll to August 4th
* open Dresden Harley Days 2017 at 10:00 -> Description present
* go back
* open Dresden Harley Days 2017 again -> Description absent

See the attached screen shot. This was the very first event for which I noticed the issue yesterday. For other events it still works.
![device-2017-07-27-090107](https://user-images.githubusercontent.com/1614987/28658141-33fb3662-72aa-11e7-8761-1bbf5af1a261.png)

**Comment by dmfs** [comment]
After that happened, the description is missing for a lot of events. I can't say if I opened them all before though.

**Comment by dmfs** [comment]
I just opened the Harley Days again (without closing the app) and after loading the event from the API the description is now present again:
![device-2017-07-27-091325](https://user-images.githubusercontent.com/1614987/28658492-e36d3da6-72ab-11e7-8f4a-452b8928159f.png)

**Comment by dmfs** [comment]
But I might have rotated the device.
And when opening it the next time -> description is gone.
