### ISSUE TITLE
School Holiday App icons for iOS

### ISSUE THREAD

**Issue by wilfredstegeman** [schedjoules/android-event-discovery-sdk#432]

**Comment by rutgerg** [comment]
I don't see icon at https://london.schedjoules.com/apps/412/edit?locale=en yet. Where did you put them?

**Comment by wilfredstegeman** [comment]
I uploaded them to a new folder apps/1295121238/

**Comment by rutgerg** [comment]
To staging; not production. I just deployed to production

**Comment by rutgerg** [comment]
Sizes like Default-568h@2x~iphone and Default@2x~iphone and couple of others are not needed anymore?

**Comment by wilfredstegeman** [comment]
The default images were opening screens that we don't use anymore indeed. Do you miss any icons as well or only these default images?

**Comment by dmfs** [comment]
Issue moved to [schedjoules/iOS-SDK #5](https://github.com/schedjoules/iOS-SDK/issues/5) via [**ZenHub**](https://www.zenhub.com/)
