### ISSUE TITLE
In order to get feedback we need to replace current button

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#61]
@rutgerg commented on [Mon Dec 12 2016](https://github.com/schedjoules/backlog/issues/83)

---

@wilfredstegeman commented on [Thu Dec 29 2016](https://github.com/schedjoules/backlog/issues/83#issuecomment-269631415)

![listviewnosettings](https://cloud.githubusercontent.com/assets/5968782/21545052/aa6c568a-cdd4-11e6-914b-a9dcecd59fd6.png)
![listviewsettings](https://cloud.githubusercontent.com/assets/5968782/21545053/aa6e7726-cdd4-11e6-8c1b-672d0e7a1715.png)

---

@lemonboston commented on [Thu Dec 29 2016](https://github.com/schedjoules/backlog/issues/83#issuecomment-269641898)

@wilfredstegeman So the feedback button would simply go into an [overflow menu](https://material.io/guidelines/components/menus.html), correct? (A "Feedback" item shown when the 3 dots is pressed.)

Okay to move this issue to the sdk repository and start working on it?

---

@wilfredstegeman commented on [Thu Dec 29 2016](https://github.com/schedjoules/backlog/issues/83#issuecomment-269645732)

Yes.

**Comment by lemonboston** [comment]
Could someone please provide the translations in German and Dutch for the menu item label "Feedback"?

**Comment by wilfredstegeman** [comment]
@lemonboston you can use Feedback both in German as in Dutch.

**Comment by lemonboston** [comment]
Ok, thanks.

**Comment by dmfs** [comment]
@lemonboston FYI: I've released java-api-client 0.4.4 which contains the ApiQuery to resolve the feedback form url. After merging the MicroFragments branch we should use it to create a loader MicroFragment and proceed to a WebviewMicroFragment when the URL was loaded.
