### ISSUE TITLE
Event details keeps loading if app was put to background and resumed

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#65]
When home button is pressed while the details screen is loading and then the app is resumed, the loading indication can go on forever without loading the screen.
This doesn't happen always.

**Comment by dmfs** [comment]
Should be fixed by #71 
@lemonboston  please verify.

**Comment by lemonboston** [comment]
Seems good, cannot reproduce it with 'master' version now.
