### ISSUE TITLE
In order to display parsed html properly SDK needs render HTML

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#68]
@rutgerg commented on [Tue Jan 03 2017](https://github.com/schedjoules/backlog/issues/106)

---

@rutgerg commented on [Tue Jan 03 2017](https://github.com/schedjoules/backlog/issues/106#issuecomment-270160346)

Can we make a html renderer to pick and choose which tags to parse and how? Eg convert all <hx> to <h5>?

---

@dmfs commented on [Tue Jan 03 2017](https://github.com/schedjoules/backlog/issues/106#issuecomment-270223018)

The easiest way is probably to use Android's `Html.fromHtml` method and process the resulting `Spannable` in order to remove/replace all styles we don't support.

@lemonboston any other ideas?

---

@lemonboston commented on [Wed Jan 04 2017](https://github.com/schedjoules/backlog/issues/106#issuecomment-270363928)

I am not sure, is it possible to remove styles from `Spannable`?

But I would like ask some questions first:

- Do we do this processing on the client side then? Is it only for easier solution because Android already has html renderer?
- I wasn't convinced myself yet if rendering the html instead of showing the plain text extract is better, but I haven't worked with htmls much. Could we maybe build some test versions of the app that points to an endpoint that uses Meetup events so that all 3 of us can actually check how they look like? (it can be done quickly)
Btw, is there maybe a Dropbox team account or anything else where we can quickly put up apks, screenshots, screen videos? Or should we make Slack channels for it? (not sure about it's storage limit)
I would also check on meetup.com, how a description is made and check examples to have a better picture.

---

@dmfs commented on [Wed Jan 04 2017](https://github.com/schedjoules/backlog/issues/106#issuecomment-270402760)

We're talking about two steps here:
- sanitize the HTML, i.e. remove/replace all unsupported tags
- render the sanitized HTML and apply custom styles

As I mentioned somewhere else, ideally the server already returns this sanitized HTML, so we don't need to do that on the client side.

However, we still might want to influence the way it's actually rendered by TextView. That also includes the font size of headlines.

---

@lemonboston commented on [Wed Jan 04 2017](https://github.com/schedjoules/backlog/issues/106#issuecomment-270417419)

@rutgerg Do you maybe have a server endpoint or request parameter that we can use to check the Meetup events?

---

@lemonboston commented on [Wed Jan 04 2017](https://github.com/schedjoules/backlog/issues/106#issuecomment-270422248)

.. so current demo app already shows meetup events, some example:
Jan 11 21:15 Guitar..
Jan 21 21:30 The Mastersons
Jan 28 21:00 Ace of Spades

**Comment by lemonboston** [comment]
`stories/65-html-rendering` branch has been created for this.
I've added a temporary util to be able to switch easily between rendering modes on the UI: by long pressing on the description, this initial version now switches between raw string and full html rendering.

About the image rendering, we can pass in an `ImageGetter` to the Android Html call:
`Html.fromHtml(source, flags, imageGetter, tagHandler)`

https://developer.android.com/reference/android/text/Html.html#fromHtml(java.lang.String, int, android.text.Html.ImageGetter, android.text.Html.TagHandler)

(Unfortunately the TagHandler is only called for unknown tags as per the docs.)

**Comment by lemonboston** [comment]
Added mode that sort of 'extracts' the plain text (`Html.fromHtml(raw).toString()`)

**Comment by dmfs** [comment]
Here is a list of tags supported by TextView: https://commonsware.com/blog/Android/2010/05/26/html-tags-supported-by-textview.html

I suggest we retain the following tags and strip everything else:

* `<a href="...">`
* `<b>`
* `<blockquote>`
* `<br>`
* `<cite>`
* `<dfn>`
* `<div>`
* `<em>`
* `<h1>`, `<h2>`, `<h3>`, `<h4>`, `<h5>`, `<h6>`, though we should render them all at the same size (or maybe two, one for h1-h3 and a smaller one for h4-h6)
* `<i>`
* `<p>`
* `<strike>`
* `<strong>`
* `<sub>`
* `<sup>`
* `<tt>`
* `<u>`

We shouldn't support `<big>` and `<small>`

**Comment by rutgerg** [comment]
https://github.com/rails/rails-html-sanitizer
