### ISSUE TITLE
Top sticky header flashes when previous page loaded

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#69]
Unfortunately it still happens that the top sticky day header flashes when the previous page items are loaded on top of it.
It consistently happens now, but other times it doesn't do this at all.

**Comment by lemonboston** [comment]
Now it happens only after I change the location (and the search is not from today).

**Comment by lemonboston** [comment]
PR #124 should have fixed this, except for the case when we change the location, I create a separate one for that: https://github.com/schedjoules/android-event-discovery-sdk/issues/131

**Comment by dmfs** [comment]
PR #124 sort of fixed it. The header no longer flashes, but instead it disappears until the top of the section that was loaded has been reached.

**Comment by lemonboston** [comment]
Yes, I was aware of that, I forgot to mention. I tried now to apply a similar workaround for that as for the non-merging case, it doesn't work fully well, so it needs a bit more time probably to figure something out.
I've created a more specific bug for this case, so this can be closed: https://github.com/schedjoules/android-event-discovery-sdk/issues/132

**Comment by dmfs** [comment]
Moved it to done.
