### ISSUE TITLE
Stuck top day header

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-event-discovery-sdk#70]
What I was doing:
List screen with Amsterdam, open location selector, select Rotterdam, coming back to List screen, it updated to this:

![double-tomorrow](https://cloud.githubusercontent.com/assets/1077972/21694252/8fb44ac2-d384-11e6-961d-7a376591492d.png)

**Comment by dmfs** [comment]
Had a similar issue today:
![screenshot_2017-01-09-17-26-02](https://cloud.githubusercontent.com/assets/1614987/21787153/dee4b26c-d6c7-11e6-90c6-7046265e5f00.png)

**Comment by lemonboston** [comment]
Some foundings so far:

After about 15 minutes of trying I could reproduce the bug, the screeshot:
![double-header](https://cloud.githubusercontent.com/assets/1077972/21933042/f2bc5ec8-d9a3-11e6-8d57-10f29fb463c3.png)

I could debug the code and also inspect the view hierarchy and that stuck header element is not there in the adapter's list (not in FlexibleAdapter's internal list and not in our own list), so the lists are correct, but it is the first child of the RecyclerView in the view hierarchy.
It stays there even after selecting another location again.

Here is the comparison of the attributes of the FrameLayout showing this stuck day header and another FrameLayout that is a correct day header in the list:
![compare2](https://cloud.githubusercontent.com/assets/1077972/21933350/5c5cce2a-d9a5-11e6-8629-a4dcb2fda45a.png)

What may be interesting is that FORCE_LAYOUT flag in the stuck header.
In `ViewGroup`, there is this usage:
```
    /**
     * Prevents the specified child to be laid out during the next layout pass.
     *
     * @param child the child on which to perform the cleanup
     */
    protected void cleanupLayoutState(View child) {
        child.mPrivateFlags &= ~View.PFLAG_FORCE_LAYOUT;
    }
```
So I suppose it might suggest that something went wrong with the layout() cycles.

A screen video of the behaviour of this stuck header:
https://drive.google.com/open?id=0Bzp0PP6UbK4lS3BTN1ZQN3BKSkk
The view hierarchy file, can be opened in Android Studio:
https://drive.google.com/open?id=0Bzp0PP6UbK4lSUgzekRIV2lrN3M

**Comment by lemonboston** [comment]
The FlexibleAdapter is currently cleared by calling this:
```
mFlexibleAdapter.removeRange(0, totalSize);
```
But there is also a clear() method, that is implemented like this:
```
	public void clear() {
		if (DEBUG) Log.d(TAG, "clearAll views");
		removeAllScrollableHeaders();
		removeAllScrollableFooters();
		removeRange(0, getItemCount(), null);
	}
```
So this could have been the cause, to simply call clear() instead, but when I reproduced the bug I had already changed that, so that happened with calling clear().

**Comment by lemonboston** [comment]
As a next step I wanted to update `FlexibleAdapter` to latest version and also replacing the mentioned removeRange() call to clear() and see if I can still reproduce the bug, maybe it has been fixed in the library already.
I couldn't update to latest `61ab9e96` (2017 Jan 12) version because I got this error:
```
android-event-discovery-sdk/eventdiscovery-demo/build/intermediates/data-binding-layout-out/debug/values-v24/values-v24.xml
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
```
It is caused by `FlexibleAdapter` update to support library 25.1.0 from 25.0.1, although I don't know the exact problem and whether it could be fixed, but I used an earlier version instead, the commit from before the support lib update:
`1ca6f3b47` (2016 Dec 15 - before upgrading to 25.1.0)

So this 2 changes are now in `bugs/70-stuck-header` branch.
I tried to reproduce the bug with this version by playing with it for about 10 minutes but I couldn't. Unfortunately this doesn't means it is fixed, because the bug happened only now and then before as well.

I am going to create an issue on FlexibleAdapter github, so the developer can have a look, maybe he knows what is happening with this bug. I plan to include the details of our usage as well, the calls we use from FlexibleAdapter, so also reviewing our usage at the same time.
In particular, this log message might worth looking into, too:
```
W/View: requestLayout() improperly called by android.widget.FrameLayout{cd22701 V.E...... ......ID 0,0-1080,95} during layout: running second layout pass
E/FlexibleAdapter: addItems No items to add!
```

**Comment by lemonboston** [comment]
Status:

From the investigation it looks like a non-trivial bug, probably caused by the FlexibleAdapter library.
(The stuck header android.View is the first child of the RecyclerView, but it is not in the list of items kept by FlexibleAdapter.)

Plan is to first update FlexibleAdapter to latest version and make sure we use it according to their documentation. It turned out we didn't so a first PR was made and merged already about the version update and some smaller changes. A second, bigger refactor will come, it is started already but the UI test from #56 are needed first to continue with that.

After refactors are done we can check if bug(s) still happen, if they do, we can file an issue on FlexibleAdapter github page.

**Comment by lemonboston** [comment]
Work items on the FlexibleAdapter usage refactor (continuously updated):

- [x] Update left-off branch with master, cleanup after merge, create 'squashed and rebased' state

- [x] Update event list items merging unit test

**Comment by lemonboston** [comment]
The FlexibleAdapter usage update is done in #124.

As I haven't encountered and haven't been able reproduce the stuck header bug recently, I would say that if you @dmfs try to reproduce it as well and you can't, then we could close this bug for now.
If it comes back we would need to open a bug on FlexibleAdapter github.

**Comment by lemonboston** [comment]
The related PR #124 has been submitted to review. That is aimed to update `FlexibleAdapter` usage in general which may fix this bug. As I haven't encountered this bug in the last few weeks, I put this in review as well along with the PR.

**Comment by dmfs** [comment]
Fixed.
