### ISSUE TITLE
In order to search events at my current location, as a user I want an option to "pick" my "current location" in the LoPi.

### ISSUE THREAD

**Issue by dmfs** [schedjoules/android-event-discovery-sdk#95]
The behavior is expected to be as follows:
* if visible, the "current location" module is always the topmost item
* the "current location" item has no section header
* on Android 5.x and lower the "current location" item is only visible if the app has location permission (either coarse or GPS)
* on Android 6 the item is always visible
* if the permission has already been granted the item contains the current location (The name of the city and country should be sufficient) and clicking the item will accept it as the result
* if the permission has not been granted, the title is "Current location" and clicking it will open the permission consent screen. If the permission has been granted the location picker will close and use the current location without any addition click. Otherwise it will show a message like "To use your current location, please grant permission to access your location." and return to the picker.
* If the permission has been granted but the location is not known yet (i.e. not GPS fix yet), we show a subtle indeterminate progress animation ("locating you ...")

**Comment by lemonboston** [comment]
ETA for this story was end of today (Wednesday) but it will be delayed. It took longer to finish the changes and prepare the code for the first pull request #126 . And there are still things to implement and discuss (see in PR).
New ETA depends on some of those questions, so a new, conservative estimation is end of Friday.
